### ISSUE TITLE
How do you use it?

### ISSUE THREAD

**Issue by mongrelion** [ibaranov-cp/Ergo_Infinity_Display#1]
I really am not a Python developer so I don't really know what's going on and it sounds like a lot of work to go through the code to figure out how to use this.
Perhaps you could include some basic steps on how to get this working on the README file?

Cheers!

**Comment by ibaranov-cp** [comment]
Hello!

Good idea, this will be done right away.

**Comment by ibaranov-cp** [comment]
Going to close this one.
